name: Sync Fork

on:
  push:
  schedule:
    - cron: '* */24 * * *' # one time every day
  workflow_dispatch: # on button click

jobs:
  repo-sync: 
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: ShiqiYu
          base: master
          head: master
